runtime: php74

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: auto

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve php scripts.
- url: /(.+\.php)$
  script: auto

runtime_config:
  document_root: . 