runtime: php74
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: index.php

- url: /.*
  static_dir: .

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

runtime_config:
  document_root: . 